# NumPy - Numerical Python

### What is Numpy?
- Package for Numerical computing in Python.
- It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

### Core Features of NumPy Arrays:
- Fixed Size: Once created, the size of a NumPy array is immutable. Resizing creates a new array.
- Homogeneous Data Type: All elements must be of the same data type, ensuring consistent memory usage.
- Efficient Operations: Supports fast, vectorized operations on large datasets with minimal code.
- Memory Efficiency: Arrays are stored in contiguous blocks of memory, making access and computation faster.
- Multidimensional Support: Easily handles 1D, 2D, and higher-dimensional arrays.

### Creating NumPy Arrays

In [1]:
# import numpy
import numpy as np

In [2]:
# NumPy arrays are created from Python lists and tuples,

a = np.array([1,2,3,4,5])  # list input
b = np.array((1,4,5,6,98)) # tuple input

print(a,type(a))
print(b,type(b))

[1 2 3 4 5] <class 'numpy.ndarray'>
[ 1  4  5  6 98] <class 'numpy.ndarray'>


In [3]:
# 1D array : Vector  
# Ex. Feature vector
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# 2D array : Matrix
# Ex. Linear algebra, image data
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3D array (Multi-dimenstional) : Tensor
# Deep Learning
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# dtype :  set the data type explicitly when creating an array

a = (0,1,2,0,3,5)

print(np.array(a,dtype=int))
print(np.array(a,dtype=float))
print(np.array(a,dtype=complex))
print(np.array(a,dtype=bool))
print(np.array(a,dtype=str))

[0 1 2 0 3 5]
[0. 1. 2. 0. 3. 5.]
[0.+0.j 1.+0.j 2.+0.j 0.+0.j 3.+0.j 5.+0.j]
[False  True  True False  True  True]
['0' '1' '2' '0' '3' '5']


### Range based creation:

In [7]:
# arange(start,end,stepsize)

print(np.arange(1,7)) # default step size = 1
print(np.arange(1,20,2))
print(np.arange(-5,5))

[1 2 3 4 5 6]
[ 1  3  5  7  9 11 13 15 17 19]
[-5 -4 -3 -2 -1  0  1  2  3  4]


In [8]:
# linspace(start,end,num) : create evenly spaced values over a specified interval.

print(np.linspace(0,20,5))
print(np.linspace(0,1,5))
print(np.linspace(1,100,dtype=int))  # default num = 50
print(np.linspace(1,100))

[ 0.  5. 10. 15. 20.]
[0.   0.25 0.5  0.75 1.  ]
[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97 100]
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


### Using Built-in functions

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [12]:
# square Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# Non-square identity matrix
np.eye(4,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [14]:
# creates any empty array without initializing its values.
np.empty((2,2)) # unintialized values (garbage values from memory)

array([[1., 1.],
       [1., 1.]])

### Random Arrays

In [15]:
# random floats between 0 and 1
np.random.rand(2,3)

array([[0.72704071, 0.16709848, 0.11387974],
       [0.28806849, 0.93683512, 0.19633266]])

In [16]:
# random integers between given interval
np.random.randint(1,10,(2,2))

array([[4, 1],
       [6, 9]], dtype=int32)

In [17]:
# random floats with normal distribution (mean=0,std=1)
np.random.randn(3,3)

array([[ 0.88815882, -2.26976531, -0.99901245],
       [ 0.11409611, -0.43030082, -0.3748663 ],
       [ 0.74970569,  1.79542438,  1.12191486]])

### Reshape after creation

In [18]:
a = np.array([1,2,3,4,5,6,7,7,8,9])
print(a)

[1 2 3 4 5 6 7 7 8 9]


In [19]:
a.reshape((2,5))

array([[1, 2, 3, 4, 5],
       [6, 7, 7, 8, 9]])

# Array Attributes

In [20]:
# create arrays
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [21]:
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [22]:
# ndim - Number of dimensions
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [23]:
# shape - array dimensions (no. of items in each dimensions)
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [24]:
# size - total number of elements
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [25]:
# dtype - Datatype of array elements
# int32 --> less size
# int64 --> more size
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [26]:
# itemsize - memory occupied by each element of an array (size in bytes)
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [27]:
# nbytes - total bytes consumed by the array (elements * bytes by each element)
print(a1.nbytes)
print(a2.nbytes)
print(a3.nbytes)

80
96
64


In [28]:
# Transpose - Transpose of the array
print(a2)
print(a2.T)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]


In [29]:
np.transpose(a3)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [30]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### Changing Data Type

In [31]:
# astype - to convert a array to a different data type
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a3.dtype

dtype('int64')

In [33]:
a3.astype(np.float64)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

# Array Operations
- Numpy supports powerful, vectorized operations on arrays.
- Operations are applied to all elements at once, making them fast and efficient.

In [34]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [35]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### 1. Arithmatic Operations

In [37]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
# Scaler Addition
a1 + 2.7

array([[ 2.7,  3.7,  4.7,  5.7],
       [ 6.7,  7.7,  8.7,  9.7],
       [10.7, 11.7, 12.7, 13.7]])

In [39]:
# Vector Addition
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [40]:
# Scaler Subtraction
a1 - 4

array([[-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [41]:
# Vector Subtraction
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [42]:
# Scaler Multiplication
a1*7

array([[ 0,  7, 14, 21],
       [28, 35, 42, 49],
       [56, 63, 70, 77]])

In [43]:
# Vector Multiplication

a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [44]:
# Scaler Division
a1/6

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.66666667, 0.83333333, 1.        , 1.16666667],
       [1.33333333, 1.5       , 1.66666667, 1.83333333]])

In [45]:
# Vector Division
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [46]:
# Scaler Int Division
a1//6

array([[0, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 1, 1]])

In [47]:
# Vector Int Division
a1//a2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
# modulo - return the remainder.
a1%3

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]])

In [49]:
# modulo
a1%a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# power
a1**3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [51]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### 2. Comparison Operations

In [52]:
a1 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [53]:
a1 == a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [54]:
a1 >= 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
a1 >= a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [56]:
a1 <= 10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [57]:
a1 <= a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### 3. Logical Operations

In [58]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [59]:
np.logical_and(a1>4,a2>8)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
np.logical_or(a1>5,a1>8)

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
np.logical_not(a1>8)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

### 4. Aggregate/Reduction Operations

In [62]:
a = np.random.randint(1,20,(3,4))
a

array([[14, 13, 16, 11],
       [ 7,  1,  6,  5],
       [ 9, 14, 11, 11]], dtype=int32)

In [63]:
print(a.sum())
print(a.min())
print(a.max())
print(a.mean()) 
print(a.std()) # standard deviation
print(a.prod()) # product of all elements

118
1
16
9.833333333333334
4.199867722784718
102555573120


### 5. Matrix Operations

In [64]:
a = np.arange(12).reshape(3,4)
b = np.random.randint(1,20,12).reshape(4,3)

In [65]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
b

array([[ 8, 15,  6],
       [12, 10, 17],
       [ 1, 14, 12],
       [10,  5,  9]], dtype=int32)

In [67]:
# Transpose : rows to columns and vice versa
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [68]:
# dot product
# 3*4 . 4*3 ==> 3*3
a.dot(b)

array([[ 44,  53,  68],
       [168, 229, 244],
       [292, 405, 420]])

In [69]:
np.matmul(a,b) # same as dot product

array([[ 44,  53,  68],
       [168, 229, 244],
       [292, 405, 420]])

# Array Functions

In [70]:
a1 = np.random.random((3,3))*100
a1

array([[18.83328706, 35.71052928, 87.93934675],
       [95.82332979, 81.02560758, 61.65963076],
       [37.38768124, 76.77504829, 95.75930059]])

In [71]:
np.round(a1,2)

array([[18.83, 35.71, 87.94],
       [95.82, 81.03, 61.66],
       [37.39, 76.78, 95.76]])

In [72]:
np.mean(a1)

np.float64(65.65708459298817)

In [73]:
np.median(a1)

np.float64(76.77504828604602)

In [74]:
np.std(a1)

np.float64(27.032590563056605)

In [75]:
np.var(a1)

np.float64(730.7609525498569)

In [76]:
np.sin(a1)

array([[-0.01626814, -0.91398939, -0.02524487],
       [ 0.9999887 , -0.60979461, -0.92161536],
       [-0.30642074,  0.9812464 ,  0.99824373]])

In [77]:
np.log(a1)

array([[2.93562589, 3.57544558, 4.47664734],
       [4.56250618, 4.39476525, 4.12162943],
       [3.62134127, 4.3408797 , 4.56183776]])

In [78]:
np.exp(a1)

array([[1.51075015e+08, 3.22764539e+15, 1.55443668e+38],
       [4.12613436e+41, 1.54516288e+35, 6.00395452e+26],
       [1.72688594e+16, 2.20282410e+33, 3.87022164e+41]])

In [79]:
np.floor(a1)

array([[18., 35., 87.],
       [95., 81., 61.],
       [37., 76., 95.]])

In [80]:
np.ceil(a1)

array([[19., 36., 88.],
       [96., 82., 62.],
       [38., 77., 96.]])

# Indexing and Slicing

In [81]:
a1 = np.arange(10) # 1D array
a2 = np.arange(12).reshape(3,4) # 2D array
a3 = np.arange(8).reshape(2,2,2) # 3D array

In [82]:
# Indexing in 1D array

In [83]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a1[5]

np.int64(5)

In [85]:
a1[-1]

np.int64(9)

In [86]:
# Indexing in 2D array

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a2[1]

array([4, 5, 6, 7])

In [89]:
a2[1][2]

np.int64(6)

In [90]:
a2[1,2]

np.int64(6)

In [91]:
a2[-1,-1]

np.int64(11)

In [92]:
a2[-1][-1]

np.int64(11)

In [93]:
# Indexing in 3D array

In [94]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
a3[0]

array([[0, 1],
       [2, 3]])

In [96]:
a3[0][0]

array([0, 1])

In [97]:
a3[0][0][0]

np.int64(0)

In [98]:
a3[1,1,1]

np.int64(7)

In [99]:
a3[0,0,0]

np.int64(0)

In [100]:
a3[1,1,0]

np.int64(6)

In [101]:
# Slicing in 1D array

In [102]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a1[5:]

array([5, 6, 7, 8, 9])

In [104]:
a1[5:7]

array([5, 6])

In [105]:
a1[1:8:2]

array([1, 3, 5, 7])

In [106]:
# Slicing in 2D array

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a2[0]

array([0, 1, 2, 3])

In [109]:
a2[0,:]

array([0, 1, 2, 3])

In [110]:
a2[:,2]

array([ 2,  6, 10])

In [111]:
a2[:,0:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [112]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [113]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [114]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [116]:
a2[1,::3]

array([4, 7])

In [117]:
a2[:-1,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [118]:
# Slicing in 3D array

In [119]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [120]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [121]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
a3[0,1]

array([3, 4, 5])

In [123]:
a3[1,::,1]

array([10, 13, 16])

In [124]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [125]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# np.nan in NumPy
- stands for 'Not a Number'.
- represents missing or undefined values.

In [126]:
a = np.array([1,2,4,5,6,np.nan,9,5,np.nan])
a

array([ 1.,  2.,  4.,  5.,  6., nan,  9.,  5., nan])

In [127]:
a[5]

np.float64(nan)

In [128]:
a[5] == np.nan

np.False_

In [129]:
# np.nan is not equal to anything, not even itself.
np.nan == np.nan

False

In [130]:
# np.isnan() -  to check for NaN.
np.isnan(np.nan)

np.True_

In [131]:
np.isnan(a[5])

np.True_

# Iteration in array

In [132]:
# 1D array
a1  = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
for i in a1:
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [134]:
# 2D array
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
for i in a2:
    print(i,end=', ')

[0 1 2 3], [4 5 6 7], [ 8  9 10 11], 

In [136]:
# nditer - to iterate over every element in the array, regardless of its shape or dimensions.
for i in np.nditer(a2):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [137]:
# ndenumerate - returns pairs of (index_tuple, value) for each element in the array.
for index,value in np.ndenumerate(a2):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


In [138]:
# 3D array
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
for i in a3:
    print(i,end='\n\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[18 19 20]
 [21 22 23]
 [24 25 26]]



In [140]:
# nditer - to iterate over every element in the array, regardless of its shape or dimensions.
for i in np.nditer(a3):
    print(i,end=', ')

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 

In [141]:
# ndenumerate - returns pairs of (index_tuple, value) for each element in the array.
for index,value in np.ndenumerate(a3):
    print(index,value)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(0, 2, 0) 6
(0, 2, 1) 7
(0, 2, 2) 8
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 1, 0) 12
(1, 1, 1) 13
(1, 1, 2) 14
(1, 2, 0) 15
(1, 2, 1) 16
(1, 2, 2) 17
(2, 0, 0) 18
(2, 0, 1) 19
(2, 0, 2) 20
(2, 1, 0) 21
(2, 1, 1) 22
(2, 1, 2) 23
(2, 2, 0) 24
(2, 2, 1) 25
(2, 2, 2) 26


# Reshaping

In [142]:
a1 = np.random.randint(1,100,12)
a1

array([42, 52, 66, 81, 29, 44, 77, 81, 60, 93, 26,  1], dtype=int32)

In [143]:
# reshape
a1 = a1.reshape(3,4)
a1

array([[42, 52, 66, 81],
       [29, 44, 77, 81],
       [60, 93, 26,  1]], dtype=int32)

In [144]:
a2 = a1.reshape(6,2)
a2

array([[42, 52],
       [66, 81],
       [29, 44],
       [77, 81],
       [60, 93],
       [26,  1]], dtype=int32)

In [145]:
# Transpose
np.transpose(a1)

array([[42, 29, 60],
       [52, 44, 93],
       [66, 77, 26],
       [81, 81,  1]], dtype=int32)

In [146]:
# Transpose - 2nd way
a1.T

array([[42, 29, 60],
       [52, 44, 93],
       [66, 77, 26],
       [81, 81,  1]], dtype=int32)

In [147]:
# ravel - used to flatten any multi-dimensional array into a 1-D array.
a1.ravel()

array([42, 52, 66, 81, 29, 44, 77, 81, 60, 93, 26,  1], dtype=int32)

# Stacking

In [148]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [149]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [151]:
# horizontal stacking 
np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [152]:
np.hstack((a1,a1,a2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11,  8,  9, 10, 11, 20, 21, 22, 23]])

In [153]:
# vertical stacking
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [154]:
a1 = np.arange(12).reshape(2,6)
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [155]:
# horizontal splitting
np.hsplit(a1,2) # 2 equal parts

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [156]:
np.hsplit(a1,3) # 3 equal parts

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [157]:
a1 = np.transpose(a1)
a1

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [158]:
# vertical splitting
np.vsplit(a1,2) # 2 parts

[array([[0, 6],
        [1, 7],
        [2, 8]]),
 array([[ 3,  9],
        [ 4, 10],
        [ 5, 11]])]

In [159]:
np.vsplit(a1,3) # 3 parts

[array([[0, 6],
        [1, 7]]),
 array([[2, 8],
        [3, 9]]),
 array([[ 4, 10],
        [ 5, 11]])]

# Row/Column wise Operations

In [160]:
# 1D array
a1 = np.array([1,2,3,4,5,6,7])
a1

array([1, 2, 3, 4, 5, 6, 7])

In [161]:
np.sum(a1)

np.int64(28)

In [162]:
# 2D array
a2 = np.random.randint(1,12,12).reshape(4,3)
a2

array([[ 2,  4,  2],
       [ 5, 10,  3],
       [ 6,  8, 11],
       [ 7,  3,  5]], dtype=int32)

In [163]:
for i,j in enumerate(a2):
    print('Row',i,':',j)

Row 0 : [2 4 2]
Row 1 : [ 5 10  3]
Row 2 : [ 6  8 11]
Row 3 : [7 3 5]


In [164]:
a2.shape

(4, 3)

In [165]:
# axis = 0 : column wise sum
# result shape : 3
np.sum(a2,axis=0) 

array([20, 25, 21])

In [166]:
# axis = 1 : row wise sum
# result shape : 4
np.sum(a2,axis=1)

array([ 8, 18, 25, 15])

In [167]:
# 3D array
a3 = np.arange(24).reshape(2,3,4)
a3


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [168]:
a3.shape

(2, 3, 4)

In [169]:
# result shape : (3,4)
np.sum(a3,axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [170]:
# result shape : (2,4)
np.sum(a3,axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [171]:
# result shape : (2,3)
np.sum(a3,axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])